version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PW}
      MYSQL_ROOT_PASSWORD: ${DB_PW}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-sql:/var/lib/mysql
  main:
    build: .
    # image: ${IMAGE_NAME}
    image: hogwarts-but-better-bot
    environment:
      - TOKEN=${TOKEN}
      - DB_URL=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PW=${DB_PW}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=development
    depends_on:
      - db
volumes:
  my-sql: